### PR TITLE
added confirm password #347

### PR DESCRIPTION
**Pull request by ankita685**
added confirm password functionality

### CODE REVIEW

**Comment by sk66641** [comment]
@ankita685 
please mention the assigned issue number

**Comment by ankita685** [comment]
> @ankita685 please mention the assigned issue number

#347

**Comment by ankita685** [comment]
hwy please merge my pr under gssoc 2024

**Comment by sk66641** [comment]
@ankita685 
once checkout [guidelines](https://github.com/sk66641/Random-Disco-Light-Simulator#getting-started)

**Comment by ankita685** [comment]
> @ankita685 you can once checkout [guidelines](https://github.com/sk66641/Random-Disco-Light-Simulator#getting-started)

hey its neeb more than 5 daya now can you merge my pr

**Comment by sk66641** [comment]
@ankita685 
if the assignee of the issue #347 doesn't reply within two to three days, this pr will be merged.

**Pull request closed without merging**
