### PR TITLE
Updated the Light Pattern Options In website

### PR DESCRIPTION
**Pull request by vivekvardhan2810**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes:  #597 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

image

### CODE REVIEW

**Review by aditya-bhaumik — APPROVED** [review]

**Comment by aditya-bhaumik** [comment]
@sk66641 please review this pull request i am a little busy at the moment

**Comment by sk66641** [comment]
will review it before the finishing time

**Comment by sk66641** [comment]
@vivekvardhan2810 
simulation should not start before successful submission, also there should be an option for user to select none
[Screencast from 2024-08-10 11-25-52.webm](https://github.com/user-attachments/assets/676e38ae-38c5-44b5-8a1a-e608b13414a0)

**Comment by vivekvardhan2810** [comment]
Ok @sk66641 will make the required changes before the finishing time

**Comment by sk66641** [comment]
@aditya-bhaumik 
please review this pr after required changes because i might not be able to review it today

**Comment by aditya-bhaumik** [comment]
@sk66641 will you be available at 5 as I will be creating some pull requests of my own and 7 is the deadline

**Pull request merged**
