### PR TITLE
FIXED #73 : Enhanced Footer

### LINKED ISSUE #73: Improper Footer Implementation
The footer currently lacks clarity in the visibility of social media links and does not adhere to proper implementation standards. To improve this, the footer should be redesigned to include the website's name prominently, along with copyright information. Additionally, the social media links should be made more visible and accessible.

Being a GSSoC'24 contributor, I want to work on this issue.

### PR DESCRIPTION
**Pull request by AkshitGarg24**
Fixes #73 

The footer has been updated. Please see the attached screenshot for reference.

Screenshot 2024-06-01 011549

### CODE REVIEW

**Comment by AkshitGarg24** [comment]
Hi @sk66641 ,

Could you please merge my pull request at your earliest convenience?

Also, please label the PR before merging it.

Thank you!

**Comment by sk66641** [comment]
@AkshitGarg24 
there is an issue after clicking submit button. you can watch in the video, i have attached below.

https://github.com/sk66641/Random-Disco-Light-Simulator/assets/145834771/56903f82-fdc8-40ce-bb9c-86c1d9d106db

**Comment by AkshitGarg24** [comment]
@sk66641 I will fix this issue and revert back to you.

**Comment by AkshitGarg24** [comment]
@sk66641 The issue has been resolved. Please review the changes and let me know if any further adjustments are needed.

If everything is satisfactory, kindly label my PR and proceed with the merge at your earliest convenience.

Thank you!

**Pull request merged**
