### PR TITLE
Customization Options

### PR DESCRIPTION
**Pull request by P-lavanya16**
Screenshot (102)
Issue no:#29

### CODE REVIEW

**Comment by sk66641** [comment]
@P-lavanya16 there are some issues like, dimensions of box are getting changed after clicking submit button
[Screencast from 28-05-24 03:41:36 PM IST.webm](https://github.com/sk66641/Random-Disco-Light-Simulator/assets/145834771/f70c8b41-70da-4307-b464-303ebaa80479)

**Comment by P-lavanya16** [comment]
Screenshot (106)

**Comment by sk66641** [comment]
Hi! @P-lavanya16  We appreciate the effort you put into creating this pull request. However, after review, we've noticed that there was already "time interval" option to change the speed & brightness and saturation doesn't have much effect in the simulation.
If you'd like, feel free to work on another issue or feature. Your contributions are valuable, and we hope to see more from you in the future!

**Comment by P-lavanya16** [comment]
@sk66641 can you please label the issue under gssoc atleast!!

**Pull request closed without merging**
