### PR TITLE
Improved , Save Preset and Load Preset Buttons with animation And also Improve the FeedBack Form

### PR DESCRIPTION
**Pull request by AbheetHacker4278**
### Description

I have Improve  the Save Preset and Load Preset Buttons with Cool and Funky Aniamtions and Also Updated the old FeedBack Form to new Elegant Animated Form , I hope You will review my PR and assign this issue to me under GSSOC24.

### Video

https://github.com/sk66641/Random-Disco-Light-Simulator/assets/114290748/bbc936f3-36df-483a-80e5-fb87eeae1666

### Images

**BEFORE**
Screenshot 2024-06-18 231845

**AFTER**
Screenshot 2024-06-18 231908

@sk66641

### CODE REVIEW

**Comment by AbheetHacker4278** [comment]
@sk66641 please checkout this PR

**Comment by AbheetHacker4278** [comment]
@sk66641 please checkout this PR

**Comment by sk66641** [comment]
@AbheetHacker4278 
Read [#guidelines](https://github.com/sk66641/Random-Disco-Light-Simulator?tab=readme-ov-file#getting-started)!

**Comment by AbheetHacker4278** [comment]
> @AbheetHacker4278 
> Read [#guidelines](https://github.com/sk66641/Random-Disco-Light-Simulator?tab=readme-ov-file#getting-started)!

Please mention the problem , so i can fix it

**Comment by AbheetHacker4278** [comment]
@sk66641 okay  , now i understand , so do i wait for my issue is been reviewed or delete this PR

**Comment by AbheetHacker4278** [comment]
@sk66641 i want to do PR under GSSOC24

**Comment by sk66641** [comment]
@AbheetHacker4278 
Keep the changes for the new feedback form & remove the changes for Save preset and Load preset button
And there is an issue in your feedback form, clicking on the submit button without filling any info makes it invisible

**Comment by AbheetHacker4278** [comment]
> @AbheetHacker4278 
> Keep the changes for the new feedback form & remove the changes for Save preset and Load preset button
> And there is an issue in your feedback form, clicking on the submit button without filling any info makes it invisible

Okay,  till tommorow i will fix this issue and i acknowledge your review very serious,  thanks for this review 😊

**Comment by AbheetHacker4278** [comment]
@sk66641 please check the feedback form , i have done necessary changes

**Comment by sk66641** [comment]
@AbheetHacker4278 
The background gets change after submitting the feedback form, i have attached a video for the reference
...

https://github.com/sk66641/Random-Disco-Light-Simulator/assets/145834771/d28bde97-074f-402c-8626-226c2eae3b4e

**Comment by AbheetHacker4278** [comment]
https://github.com/sk66641/Random-Disco-Light-Simulator/assets/114290748/4580bede-5f67-4903-ab5c-8e0d5fdfaca4

**Comment by sk66641** [comment]
@AbheetHacker4278
It's good practice to link the PR to the issue. It was #289.

**Pull request merged**
