### PR TITLE
Backbutton

### PR DESCRIPTION
**Pull request by nikhaararoraa**
Back Button added

### CODE REVIEW

**Comment by sk66641** [comment]
@nikhaararoraa 
Please mention the issue number you have been assigned for this Pull Request!

**Comment by nikhaararoraa** [comment]
#181

**Comment by sk66641** [comment]
@nikhaararoraa 
I think it's not a back button, it's a reload button which is already there, you can check.

**Comment by sk66641** [comment]
> @nikhaararoraa I think it's not a back button, it's a reload button which is already there. Could you check it once?

@nikhaararoraa

**Pull request closed without merging**
