### PR TITLE
added custom song bu import from local as well link support

### PR DESCRIPTION
**Pull request by Varsani2520**
Hey @sk66641 ,
i completed ,user can able to select the file .mp3  from computer and play music or paste url then play music

### CODE REVIEW

**Comment by Varsani2520** [comment]
also add the label as per issue no #137 and close #137

**Comment by sk66641** [comment]
@Varsani2520 
Submit button is not functioning!

https://github.com/sk66641/Random-Disco-Light-Simulator/assets/145834771/bcb8491f-e7ff-4a4c-ab4f-293da9ed8c37

**Comment by Varsani2520** [comment]
@sk66641 ,what you want to ?

**Comment by Varsani2520** [comment]
do you want to user compulsory to choose music?

**Comment by Varsani2520** [comment]
i complete the user choose song from file or paste url and click on submit then play ,its work perfectly

**Comment by sk66641** [comment]
> do you want to user compulsory to choose music?
@Varsani2520 
No, i don't want this to be compulsory but at this time it's compulsory , you can check.

**Comment by Varsani2520** [comment]
Hey @sk66641 ,check it and merge it also add the label as per issue

**Comment by sk66641** [comment]
@Varsani2520 
There is still a issue! The header is visible during loading and simulation. It'll be good if you make these changes on the current code base!

https://github.com/sk66641/Random-Disco-Light-Simulator/assets/145834771/2232c4d8-1a28-44e9-b01d-502239fa6c05

**Comment by Varsani2520** [comment]
@sk66641 ,now check it

**Comment by sk66641** [comment]
@Varsani2520 
resolve the conflicts, i'll merge it.

**Comment by Varsani2520** [comment]
Hey @sk66641 ,

i resolve the conflict ,now merge it

**Comment by Varsani2520** [comment]
also add label as per issue #137

**Pull request merged**
