### PR TITLE
Fixes #278 : Added About Page

### LINKED ISSUE #278: Replace "About" Dialog Box with Dedicated Web Page
To improve the user experience, we should replace the dialog box currently used for the About section with a dedicated web page. This will allow for a more detailed and visually appealing content presentation.

### PR DESCRIPTION
**Pull request by AkshitGarg24**
Fixes #278 

A dedicated "About" section has been added and implemented on the webpage. A reference video has also been attached. The theme of the "About" section also matches the main page theme.

https://github.com/sk66641/Random-Disco-Light-Simulator/assets/153659573/7d4bdd43-0ebd-40d2-8b2f-13f4dd76bbaf

### CODE REVIEW

**Comment by sk66641** [comment]
@AkshitGarg24 
It looks nice but there is no back button after opening about page. A back icon can be added instead of menu icon after opening of about page

**Comment by AkshitGarg24** [comment]
@sk66641 But back button is already present in browser. So if anybody wants to go back, it can be easily achieved by using the back button of the browser.

**Comment by AkshitGarg24** [comment]
Still if you want me to implement back button, I will implement it.

**Comment by sk66641** [comment]
> @sk66641 But back button is already present in browser. So if anybody wants to go back, it can be easily achieved by using the back button of the browser.

Ok, then let it be as it is

**Pull request merged**
