### PR TITLE
Issue#184#2

### PR DESCRIPTION
**Pull request by rashiranjan22**
# Description

added a preview button for songs to be selected 

Fixes:  Issue#184

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

https://github.com/sk66641/Random-Disco-Light-Simulator/assets/117447090/27964570-e07a-43fb-8d36-bd9d16f6b03e

### CODE REVIEW

**Comment by rashiranjan22** [comment]
@sk66641 please check

**Comment by sk66641** [comment]
@rashiranjan22 
mention the assigned issue number

**Comment by rashiranjan22** [comment]
> @rashiranjan22 mention the assigned issue number

its written in description 
its #184

**Comment by sk66641** [comment]
@rashiranjan22 
level updated

**Pull request merged**
