### PR TITLE
Improved FAQ Page

### LINKED ISSUE #437: 🐞[Bug]: Making UI of FAQ page similar to other pages
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The FAQ page should be made similar to other pages.

1. Proper spacing should be given between the container and the footer.
2. The background color of footer should be same as that of the background color of body, as implemented in other pages. 

### Expected behavior

Mentioned Above.

### Add ScreenShots

Footer

### What browsers are you seeing the problem on?

_No response_

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by AkshitGarg24**
Fixes #437 

The UI of the FAQ page is now similar to that of other web pages. Now the container has proper padding in the main container, the background color of the footer is now the same as the background color of the web page and there is a significant space between the container and the footer.

### CODE REVIEW

**Comment by aditya-bhaumik** [comment]
@AkshitGarg24 could you please add a screenshot

**Comment by AkshitGarg24** [comment]
Screenshot 2024-07-20 005316
Screenshot 2024-07-20 005301

**Comment by aditya-bhaumik** [comment]
@AkshitGarg24 it looks same to the one we have in the website what changes were made to the page

**Comment by aditya-bhaumik** [comment]
@AkshitGarg24 okay i am giving this pull request level 1 as some  of the work was already done and i cant find any big change in the code 
You can create another issue on some other problem with the website i will assign it to you

**Review by aditya-bhaumik — APPROVED** [review]

**Pull request merged**
