### PR TITLE
Theme toggle error

### PR DESCRIPTION
**Pull request by Jasleen1210**
# Description
Fixes theme toggle on all pages

Fixes:  #529

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### CODE REVIEW

**Comment by sk66641** [comment]
@Jasleen1210 
resolve conflicts

**Comment by Jasleen1210** [comment]
resolved! @sk66641

**Review by aditya-bhaumik — APPROVED** [review]

**Comment by aditya-bhaumik** [comment]
@Jasleen1210 please create another pr fixing this

**Comment by Jasleen1210** [comment]
@aditya-bhaumik Done! sorry for the inconvenience, not sure how this happened but i just created a new file and function for theme toggle

**Comment by sk66641** [comment]
#538

**Pull request merged**
