### PR TITLE
Adding Home icon in Privacy Policy,Terms and Conditions Page,Setting Linking and Adding Privacy Policy,Terms and Conditions Page in sidebar

### PR DESCRIPTION
**Pull request by Ojas-Arora**
# Description

@sk66641 I have made changes by Adding Home icon in Privacy Policy,Terms and Conditions Page,Setting Linking and Adding Privacy Policy,Terms and Conditions Page in sidebar. Kindly review this.

Fixes:  #413 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### CODE REVIEW

**Comment by Ojas-Arora** [comment]
@sk66641 Kindly change the label of issue from level 1 to level 2.

**Comment by sk66641** [comment]
@Ojas-Arora 
i think you have already did it in pr #403 😅

**Comment by Ojas-Arora** [comment]
@sk66641 I have not done Adding Home icon in Privacy Policy,Terms and Conditions Page,Setting Linking and Adding Privacy Policy,Terms and Conditions Page in sidebar. These file changes were not seen as they were commited due to branch updation before but I have made changes after that. Kindly assign me the level for this.

**Comment by sk66641** [comment]
@Ojas-Arora 
ok

**Comment by aditya-bhaumik** [comment]
@Ojas-Arora i think the changes are already there in the site you must have added the changes in the other pull request

**Comment by Ojas-Arora** [comment]
@aditya-bhaumik Actuaaly in my previous pr #403  due to mistake while  branch upgradation The changes of this PR were done also with that thats why It is showing now

**Comment by Ojas-Arora** [comment]
1. @aditya-bhaumik I think the level should be 2 rather than 1

**Comment by Ojas-Arora** [comment]
@aditya-bhaumik  @sk66641  Kindly please sir do the same for the level.

**Comment by Ojas-Arora** [comment]
@sk66641 Thanks sir

**Comment by sk66641** [comment]
it's ok but there's no need to call me sir 😅

**Comment by Ojas-Arora** [comment]
@sk66641 ok

**Pull request merged**
