### PR TITLE
Corrected button in all pages

### PR DESCRIPTION
**Pull request by VijaySamant4368**
# Description

Corrected the back-to-top button

Fixes:  #534 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
image

There is a problem in all the pages other than the home page that the Theme-Mode-Toggler is not working. The CSS code makes the BG of the button white, and the arrow tip black for default(light) mode. And black BG and white arrow for dark mode(As can be seen in the home page)
But in other pages, the mode-toggler is not working, and the default theme looks like dark-theme, and hence the button is white.

### CODE REVIEW

**Comment by VijaySamant4368** [comment]
@aditya-bhaumik Sorry for the inconveniences caused by my silly mistakes. Does this change looks good, or is there any other problems/specifications that I should fix?
Thank you, and I apologise once again for my mistakes.

**Review by sk66641 — APPROVED** [review]

**Comment by aditya-bhaumik** [comment]
@VijaySamant4368 please resolve the conflicts i will review by the end of the day

**Comment by aditya-bhaumik** [comment]
image
for smaller devices it is not coming properly you can use media queries to fix this rest everything looks fine

**Review by aditya-bhaumik — APPROVED** [review]

**Comment by aditya-bhaumik** [comment]
@VijaySamant4368 if you want you can work on this i will update your level to 3

**Comment by VijaySamant4368** [comment]
@aditya-bhaumik

**Comment by sk66641** [comment]
> @aditya-bhaumik I think it will be better to raise this problem as a separate issue, to prevent further conflicts, but if you say, I can do the task.

ok, resolve the conflicts once

**Comment by aditya-bhaumik** [comment]
@VijaySamant4368 resolve the conflicts make the changes carefully as i think the css code has been put in a folder

**Review by aditya-bhaumik — APPROVED** [review]

**Pull request merged**
