### PR TITLE
Added a custom scrollbar on all the pages .

### PR DESCRIPTION
**Pull request by meetarora10**
# Description
I have added a custom scrollbar to all the pages that matches with the UI of the website.

Fixes:  #488

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
Screenshot (859)
Screenshot (860)

### CODE REVIEW

**Comment by aditya-bhaumik** [comment]
@meetarora10 but this design is already there in all the pages as all the pages are linked with the styles.css i thouht you were changing the scrollbar

**Comment by meetarora10** [comment]
@aditya-bhaumik yes it was present but scrollbar was not visible in the website. So I added in individual files , trying to make it visible in all the pages .

**Comment by meetarora10** [comment]
If you say I will change the styling of the scrollbar @aditya-bhaumik

**Comment by aditya-bhaumik** [comment]
@meetarora10 it is visible as i can checked it in all pages you can try changing the scrollbar to some better design but dont remove it from the styles.css and also remove the extra code you put in html files i am closing this pr you can create another pr with the changes

Make a scrollbar which will look good with the projects color theme

**Comment by meetarora10** [comment]
Ok @aditya-bhaumik

**Pull request closed without merging**
