### PR TITLE
Added the styling to social icons and changes its placement (Final)

### PR DESCRIPTION
**Pull request by Riddhi162**
I have created another PRto make it responsive.
Fixed issue #179
Screenshot 2024-06-09 144740
Screenshot 2024-06-09 144749
For size less than 695 px i moved it to bottom to maintain good appearance

### CODE REVIEW

**Comment by Riddhi162** [comment]
[https://github.com/sk66641/Random-Disco-Light-Simulator/pull/213#issuecomment-2156177589](url)

**Comment by Riddhi162** [comment]
[](https://github.com/sk66641/Random-Disco-Light-Simulator/pull/213#issuecomment-2156177589)

**Comment by Riddhi162** [comment]
Previous Pr #213

**Comment by sk66641** [comment]
@Riddhi162 
Nice!

> I have created another PRto make it responsive. Fixed issue #179 Screenshot 2024-06-09 144740 Screenshot 2024-06-09 144749 For size less than 695 px i moved it to bottom to maintain good appearance

**Pull request merged**
