### PR TITLE
✔️ Improved "Complete UI and Functionality" Of the Feedback Form

### LINKED ISSUE #432: ➕Enhancement: Improving "Complete UI and Functionality" Of the Feedback Form
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hey @sk66641 

Here is the the Enhancement I Propose to do - 
Currently, the feedback form on the website **requires improvements to enhance user experience and functionality.** 
I **Want to make Several Enhancements** to the form to align it **better with the website theme** and improve usability.

### Here's What will I Do - 
- **Replace the current "Back to Home" button** with **a new design that matches the website's overall** color scheme and font style. And **Add hover effects** to make the button more interactive.
- **Improve the alignment and layout of the feedback form** to make it more visually appealing and user-friendly.
- **Implement tooltips for form labels** to provide additional guidance and information to users.
- **Improve the rating system by adding hover effects** to the rating stars or icons.

Please assign me this issue under GSSoC'24 
Thankyou!

### Use Case

The New UI and functionality of the form will enhance the user experience

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by aslams2020**
Hey @sk66641 and @aditya-bhaumik 
issue closes #432 

I have completely improved the Alignment, UI and functionality of the Feedback form.

### Here's What I Did 
1. I have **Completely Changed the Alignment** of the Feedback Form.
2. Added **Shining "Text Shadow" to all the labels**
3. **Added "SVG icons" in front of the labels** to improve the user experience
4. I made the form **"Fully Responsive"** for all screen-sizes 
5. **Improved the "Star-Rating" System** with Much better hovering effects and styling
6. **Changed the Wordings** of the Feedback form.

Here's the Complete Implementation -

https://github.com/user-attachments/assets/b007a718-e5ce-40df-ab53-66321c69b040

Please take a look and review it.

## Type of change
- [x] New feature (non-breaking change which adds functionality)
 
# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by aditya-bhaumik** [comment]
@aslams2020 hi there was a trail effect added to the cursor can you please add it to the feedback page also 

reference #455

**Comment by aslams2020** [comment]
@aditya-bhaumik Sure, I'll just do it

**Comment by aslams2020** [comment]
@aditya-bhaumik Done..Please check

**Comment by aditya-bhaumik** [comment]
@aslams2020 send screenshot or recording please

**Comment by aslams2020** [comment]
@aditya-bhaumik Sure..
Here's the Demo -

https://github.com/user-attachments/assets/d4f69661-0767-40e3-bdc2-01b190cddbd3

**Review by aditya-bhaumik — APPROVED** [review]

**Pull request merged**
