### PR TITLE
Add Mute Button to Simulation Page

### LINKED ISSUE #91: [Feature] : Add Mute Button to Simulation Page
### Description:
This feature involves adding a mute button to the simulation page. The mute button will allow users to mute and unmute the background music during the simulation. Initially hidden, the button will become visible when the user starts the simulation. This enhancement will provide users with greater control over their simulation experience by allowing them to easily toggle the background music on and off.

### Details:
Introduce a mute button element in the HTML code.
Initially, the mute button will be hidden using inline CSS styling (style="display:none;"). The button will be displayed dynamically using JavaScript when the user clicks the submit button to start the simulation.
Implement functionality to mute and unmute the background music when the button is clicked. This will ensure users can control the audio without needing to reload the page.
Ensure the mute button will work for all songs in the dropdown, allowing users to mute and unmute any selected background track seamlessly.
The mute button provides an additional layer of user control, enhancing the overall user experience by allowing them to manage the audio according to their preferences.
Ensure the mute button integrates seamlessly with the existing music selection dropdown and other simulation features, maintaining a clean and intuitive user interface.

### Implementation Steps:
Add a mute button element in the HTML.
Use CSS to hide the button initially.
Utilize JavaScript to make the button visible when the simulation starts.
Implement JavaScript functions to handle muting and unmuting of the background music.
Ensure the mute button's functionality works smoothly with the existing music dropdown.
Verify the mute button works for all music tracks available in the dropdown, providing consistent audio control across all selections.

### PR DESCRIPTION
**Pull request by thevijayshankersharma**
fixes #91 

This PR introduces a mute button to the simulation page, enhancing user experience by allowing them to control background music during simulations. Initially hidden, the mute button becomes visible upon starting the simulation. Users can toggle between muting and unmuting the background music without reloading the page. This feature integrates seamlessly with the existing music selection dropdown, ensuring consistent functionality across all selected tracks.

image

### CODE REVIEW

**Comment by thevijayshankersharma** [comment]
@sk66641 Check this PR.

**Comment by sk66641** [comment]
@thevijayshankersharma 
When music is changed, it doesn't work.

**Comment by thevijayshankersharma** [comment]
@sk66641 have a look now.

**Comment by sk66641** [comment]
@thevijayshankersharma 
Nice

**Comment by sk66641** [comment]
@thevijayshankersharma 
Nice, it should be level3

**Pull request merged**
