### PR TITLE
[Feature] : Implement Countdown Timer to Control Disco Light Duration

### LINKED ISSUE #23: [Feature] : Implement Countdown Timer to Control Disco Light Duration
## About the  feature
Adding a countdown timer to the Random Disco Light Simulator will enhance user control and functionality. This feature will allow users to set a specific duration for the light simulation, automatically stopping the lights and resetting the screen to its intial form when the timer reaches zero.

## Implementation 

1. Create a new input field in the inital form for the user to enter the countdown duration in seconds  
2. Implement a visible timer display that shows the countdown at the top right corner of the screen when we start the simulation
3. Develop the logic to start the countdown when the simulation begins. Ensure the timer accurately counts down and updates the display.
4. Integrate functionality to stop the light simulation when the timer reaches zero. Reset the screen to the initial form once the timer ends
5. Ensure the timer display is user-friendly and does not interfere with the visual experience of the light simulation.
6. Implement validation to ensure the countdown timer input is a positive integer and handle any invalid inputs gracefully.

@sk66641 Please assign me this under Gssoc'24

### PR DESCRIPTION
**Pull request by aditya-bhaumik**
Fixes #23 

Created a new input field in the inital form for the user to enter the countdown duration in seconds
Added a visible timer display that shows the countdown at the top right corner of the screen when we start the simulation
Added the logic to start the countdown when the simulation begins. Ensure the timer accurately counts down and updates the display.
Integrated the function to stop the light simulation when the timer reaches zero. Reset the screen to the initial form once the timer ends

https://github.com/sk66641/Random-Disco-Light-Simulator/assets/92214013/cb6a82fd-a2cb-4d2a-98f9-6d78953d3857

### CODE REVIEW

**Comment by aditya-bhaumik** [comment]
@sk66641 please review this pull request and add the gssoc labels

**Comment by aditya-bhaumik** [comment]
@sk66641 i have resolved the conflict created my the other pull request and merged the new changes to my pr 
image
image
image

**Comment by sk66641** [comment]
Nice, just there is a bug, timer should only start at the time of simulation

[Screencast from 28-05-24 03:28:20 PM IST.webm](https://github.com/sk66641/Random-Disco-Light-Simulator/assets/145834771/b3235a31-e840-4d0b-a623-7154836fa9d1)

**Comment by aditya-bhaumik** [comment]
@sk66641 i have fixed the bug now it will show this when there is no required fields filled can you please review this change please

image

**Pull request merged**
