### PR TITLE
Fixed preloader bug

### PR DESCRIPTION
**Pull request by Jasleen1210**
The particle and snowflake effect has been fixed in all the side pages.

The issue was that the preloader.css file had "display none" for the content that affected the particle effect, and the snowflake effect was preceeded by warning modal in script.js so that cause error in console.

Ive made a separate file for the preloader js and added the snowflake function in it so that all the pages have the preloader as well as the snowflake thing

Fixes:  #591 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### CODE REVIEW

**Review by aditya-bhaumik — APPROVED** [review]

**Review by sk66641 — APPROVED** [review]

**Comment by sk66641** [comment]
@Jasleen1210 
i think this change will need to be reverted , there is again the same unidentified error as it was in pr #514 .

**Comment by aditya-bhaumik** [comment]
@sk66641 yes i was also getting a similar error thats why i requested for the review 

As my network today is not working properly 

I thought it was my network problem

**Comment by Jasleen1210** [comment]
Sorry for the error, i still don't get why that error comes though, the changes made in this pr and pr 514 were not related
Ill look into it but please let me know if you have any suggestions or ideas

**Comment by sk66641** [comment]
@Jasleen1210 
is this error not occurring in your local machine?

**Comment by sk66641** [comment]
@Jasleen1210 
create another pull request with the same changes

**Comment by Jasleen1210** [comment]
Okay, i have re-forked the repo and made similar changes, please review the pr, thanks!

**Pull request merged**
