### PR TITLE
Removed negative numbering

### PR DESCRIPTION
**Pull request by ananya-dhiman**
#79 
Removed negative numbering from
1.Number of colours
2.Time interval
3.Countdown timer

### CODE REVIEW

**Comment by sk66641** [comment]
@ananya-dhiman once checkout #22

**Comment by ananya-dhiman** [comment]
Sorry I missed that issue. I have now updated the code such that the user is restricted from typing the negative bar from keyboard along with the min. I have tested and the code runs successfully. Not sure whether this is a necessary change but please check.

**Comment by sk66641** [comment]
@ananya-dhiman 
it's working but it would be great if you allow float inputs for time interval (input number 2).

**Comment by ananya-dhiman** [comment]
Ok will try to work on that, the rest don't require floats right?

**Comment by ananya-dhiman** [comment]
I have updated the code so that it allows decimal values. However it works in such a way that the user needs to type the whole number first and then add the decimal point.For values less than 0 point is added before the number after uits typed. 0 cannot be entered but that isnt hampering the final output as its considering blank as 0. I think it can be added in the blue line below just to remove confusion and as negative part isnt needed.

**Pull request merged**
