### PR TITLE
Issue #372

### PR DESCRIPTION
**Pull request by Jasleen1210**
# Description

Changed the layout of the edit button that shows up during simulation. 
Removed the independant add time button as it is already under the edit dropdown
Revised the functioning of both buttons
Added css styles in both the buttons to match the navbar styles 

Fixes:  #372 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
image

### CODE REVIEW

**Comment by sk66641** [comment]
@Jasleen1210 
level updated

**Comment by Jasleen1210** [comment]
Hello!
It appears that the changes i made to the index.html file were not reflected in the main repo even after the merge, Im not sure how this happened but since I myself was confused among the various branches of my fork, i deleted the fork altogether and fixed the issue that currently persists on the page. 
The issue is that- the edit dropdown is not working because the id used to call the dropdown in script.js was not updated in index.html, and due to this the pause feature also does not work properly.

I have now created a new fork and have made the corresponding edit,
Would you like me to add a new pull request for the same without any assigned issue? or may i create a new issue and link the pr to that, or some third option? please let me know, thanks.

**Comment by sk66641** [comment]
You can directly send a pr

**Comment by Jasleen1210** [comment]
Done!

**Pull request merged**
