### PR TITLE
[Feature] : Music Selection Dropdown during the simulation

### LINKED ISSUE #78: [Feature] : Music Selection Dropdown during the simulation
@sk66641  please assign me this under gssoc'24

This feature involves adding a music selection dropdown to the simulation page. The dropdown will allow users to choose background music for their simulation experience. Initially hidden, the dropdown will become visible after the user clicks the submit button to start the simulation. The dropdown will contain options for selecting from a variety of background music tracks, enhancing the user's experience and providing customization options.

This feature will make sure that the user does not have to reload the page to change the song they can do it while the simulation is going on. 
I would also like to remove the sound effects from the form as after adding the dropdown to the simulation section it would not be needed in the form 

This feature can help in enhancing the user experience as the user will not have to reload the page everytime they want to select a different songs lets say they are using this simulator for a long duration one song will become quiet boring having way to customize the background music can improve the overall appeal of the simulation page 

**Implementation details**
Add a <select> element in the HTML code with options for different music tracks.
Initially hide the dropdown using inline CSS styling (style="display:none;").
Show the dropdown dynamically using JavaScript when the submit button is clicked.
Implement functionality to change the background music based on the user's selection.

### PR DESCRIPTION
**Pull request by aditya-bhaumik**
**_Here's a breakdown of the feature implementation_**

Introduced a dropdown element in the HTML code, offering options for different background music tracks.

Initially, the dropdown is hidden using inline CSS styling (style="display:none;"). It becomes visible dynamically through JavaScript when the submit button is clicked to start the simulation.
Users can select background music tracks from the dropdown without reloading the page, thus improving usability and convenience.

 Sound effects were integrated into the simulation section, eliminating the need for them in the form. This streamlines the user interface and ensures consistency.
The addition of the music selection dropdown provides users with the flexibility to customize their simulation experience, enhancing overall appeal and engagement.
The implementation involved adding an HTML element with music options, dynamically showing the dropdown using JavaScript, and implementing functionality to change background music based on user selection.

Fixes #78 

### Demo video

https://github.com/sk66641/Random-Disco-Light-Simulator/assets/92214013/49ecb990-bb73-404f-8edb-b6a53d7148af

@sk66641  please review this pull request and merge this under gssoc labels

### CODE REVIEW

**Comment by sk66641** [comment]
@aditya-bhaumik 
can you add an option  "none" so that user after selecting any sound if he/she wants to deselect it, there should be an option
and make "div with id 'particles-js' " display as "none"?

**Comment by aditya-bhaumik** [comment]
@sk66641 i have added the changes you told to make but while merging the code to resolve the conflicts caused by the other pull request i by mistake made a error because of which the randomize button or the code added in the other pull request could you please help me  
Right now i have added the none as you had asked in the dropdown but the randomize button got removed and trying to add it is causing more conflicts

**Comment by sk66641** [comment]
@aditya-bhaumik 
you can revert your changes and add 'none' option and create pr, i'll try to resolve the conflicts or you can also make changes once again on the current code base.

**Comment by aditya-bhaumik** [comment]
@sk66641 i have made all the changes you requested and resolved the conflicts i was having i have created another pull request please review and merge it 
also please close this pull request thank you 

the pull request is #111

**Pull request closed without merging**
