### PR TITLE
Corrected multiple pages

### PR DESCRIPTION
**Pull request by VijaySamant4368**
# Description

Corrected all the mentioned ppages

Fixes:  #526 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### CODE REVIEW

**Comment by VijaySamant4368** [comment]
@aditya-bhaumik all right

**Comment by VijaySamant4368** [comment]
On it.

**Comment by VijaySamant4368** [comment]
Before changes:
- Width changes when toggling between modes

https://github.com/user-attachments/assets/eb8e36ad-2bf8-4c72-b665-615f45dfdca5



- Extra space in smaller screens

https://github.com/user-attachments/assets/48ddb4f9-a2cc-445f-ba51-5e8f493ad014

**Comment by VijaySamant4368** [comment]
@aditya-bhaumik please kindly have a look.
Thank you.

**Comment by sk66641** [comment]
will review it before today night

**Review by sk66641 — APPROVED** [review]

**Pull request merged**
