### PR TITLE
Corrected Back-To-Top button

### PR DESCRIPTION
**Pull request by VijaySamant4368**
# Description
Correctly matched the color theme of the back-to-top button with the background and the view mode.

Fixes:  #525

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

https://github.com/user-attachments/assets/01bdc188-3210-4d50-a939-bb06e6228f99

### CODE REVIEW

**Comment by VijaySamant4368** [comment]
@sk66641 @aditya-bhaumik plz checkout this pr.
Thank you.

**Comment by sk66641** [comment]
@VijaySamant4368 
Do you want to make a backToTopButton.css file in css folder & make changes in it & link it with all the pages where backtotopbtn is available as it makes maintenance easier. Your label will be upgraded to 2 or 3. If not, you can also proceed with the current changes.

**Comment by VijaySamant4368** [comment]
@sk66641 I will look into it.

**Comment by VijaySamant4368** [comment]
@sk66641 please check.
Thank you.

**Review by aditya-bhaumik — APPROVED** [review]

**Comment by aditya-bhaumik** [comment]
@VijaySamant4368 please resolve conflicts

**Comment by VijaySamant4368** [comment]
@aditya-bhaumik, reselved.

**Comment by aditya-bhaumik** [comment]
image

after you resolving the conflicts it is coming like this i am removing the labels for now fix the problem in another pull request or you can do it in this pull request only

**Comment by VijaySamant4368** [comment]
@aditya-bhaumik I successfully corrected the problem. Can you please add the level back?

**Comment by sk66641** [comment]
@VijaySamant4368 
i think that's already been added in your another pr #541 for the same issue #525

**Comment by aditya-bhaumik** [comment]
@VijaySamant4368 exactly i have already added the labels in the other pr 

This pull request changes were reverted thats why i had removed the labels

**Comment by VijaySamant4368** [comment]
I am sorry, I didn't notice it earlier.

**Pull request merged**
