### PR TITLE
Changed the font family and made the footer visible in light mode too 

### PR DESCRIPTION
**Pull request by Khushipawar37**
I changed the font-family to give it a more elegant look. And also the footer elements were previously not visible when changed to light mode, I fixed them and now we can view it in the same.

### CODE REVIEW

**Comment by Khushipawar37** [comment]
@sk66641 Since it is merged, please provide me the PR and appropriate level label to it.

**Comment by sk66641** [comment]
@Khushipawar37 
Can you mention the issue number you have been assigned for this PR?

**Comment by Khushipawar37** [comment]
issue #132

**Comment by Khushipawar37** [comment]
@sk66641 It is issue #92 in which I made the footer visible and changed the font family

**Pull request merged**
