### PR TITLE
Add "Preloader" to All Pages (excluding Homepage) 

### LINKED ISSUE #563: 💡[Feature]: Add Preloader to All Pages (excluding Homepage)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hey @aditya-bhaumik and @sk66641 

I’d like to create and add a preloader to all pages of the website, excludinghomepage, (which already have disco ball loader). 

### Use Case

The preloader will improve the user experience by providing visual feedback while the page content is loading.

### Benefits

N/A

### Add ScreenShots

N/A

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by MastanSayyad**
# Description

Hey @aditya-bhaumik @sk66641 

- issue fixes #563

I have added a preloader integrated with a load of percentage to all pages (excluding homepages)

- Added Preloaer which is a gradient of spinner `#ff2d15`, `#be18ff`, `#0d3dff`
- Integrated loader with `Percentage indicator: 0% to 100%` | Color gradient of `#be18ff`, `#ffffff`
- Added logic to display the preloader and update the loading percentage.
- Ensured the preloader hides and the content displays once loading is complete.
- Integrated in all pages
- Positioned in the center with `z-index: 9999;` to ensure it stays above.

https://github.com/user-attachments/assets/733197ae-c379-4da3-af22-32cecb514695

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by MastanSayyad** [comment]
Hey @aditya-bhaumik pls review this PR

**Comment by aditya-bhaumik** [comment]
@MastanSayyad i will review by the end of the day as this update is big i will have to check it in my local machine first

**Comment by aditya-bhaumik** [comment]
@MastanSayyad till then you can create another issue and start working on it

**Review by aditya-bhaumik — APPROVED** [review]

**Comment by MastanSayyad** [comment]
@aditya-bhaumik as per the changes can the level increase!

**Comment by aditya-bhaumik** [comment]
@MastanSayyad sure done

**Pull request merged**
