### PR TITLE
Adding a change/edit button

### LINKED ISSUE #182: Adding a change/edit button
Add a change/edit button to allow modifications while the disco simulator is running. This will enhance functionality and user control.
please assign this to me.

### PR DESCRIPTION
**Pull request by thevijayshankersharma**
Added a change/edit button to allow modifications while the disco simulator is running. This will enhance functionality and user control.

closes #182

### CODE REVIEW

**Comment by sk66641** [comment]
@thevijayshankersharma 
Issue #182 was supposed to add edit button which can edit inputs like number of colors, time interval & view

**Comment by thevijayshankersharma** [comment]
> @thevijayshankersharma Issue #182 was supposed to add edit button which can edit inputs like number of colors, time interval & view

I am unable to think of the logic for it. If you want, you can merge it for level 1, and the other guy can enhance this feature.

**Comment by sk66641** [comment]
@thevijayshankersharma 
ok but make the edit button only visible during the simulation & remove the add time & change music from the menu as you have included it in the "edit"

**Comment by thevijayshankersharma** [comment]
@sk66641 Done

**Pull request merged**
