### PR TITLE
Updated mode-toggler

### PR DESCRIPTION
**Pull request by VijaySamant4368**
# Description

I changed the mode toggler

Fixes:  #476

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

https://github.com/user-attachments/assets/0ba79951-56ed-4b4b-815d-0f96b804c8c0

### CODE REVIEW

**Comment by VijaySamant4368** [comment]
@aditya-bhaumik please check this out

**Comment by aditya-bhaumik** [comment]
Fixes #476

**Comment by VijaySamant4368** [comment]
I already mentioned the issue.

**Comment by aditya-bhaumik** [comment]
@VijaySamant4368 ya you mentioned it did not link it i linked it to your issue

**Comment by VijaySamant4368** [comment]
Sorry for the inconvenience.

**Review by sk66641 — APPROVED** [review]

**Comment by VijaySamant4368** [comment]
Can I get a better level? The issue is marked level 1.

**Comment by sk66641** [comment]
@VijaySamant4368 
submit button is not working i think, can you check it once?

**Comment by VijaySamant4368** [comment]
> @VijaySamant4368 submit button is not working i think, can you check it once?

I will look into it at once.

**Comment by VijaySamant4368** [comment]
@sk66641 I have changed the code and it should now ork.

**Comment by VijaySamant4368** [comment]
@sk66641 please check and merge

**Comment by sk66641** [comment]
> @sk66641 please check and merge

ok, but remove it's display after successful submission. 
Screenshot from 2024-07-23 21-44-59
You might need to make changes in function run() inside script.js
Screenshot from 2024-07-23 21-52-02

**Comment by VijaySamant4368** [comment]
On it

**Review by sk66641 — APPROVED** [review]

**Pull request merged**
