### PR TITLE
Fixes #75

### LINKED ISSUE #75: Adding a color gradient selector.
Description: Elevate your disco light experience with the Color Gradient Selector, a feature that allows you to choose a custom gradient for your light patterns.

Functionality:

Custom Color Selection: Select two or more colors to create a gradient.
Smooth Transitions: The light patterns will smoothly transition between the selected colors, creating a fluid and dynamic visual effect.
Enhanced Visuals: The gradient enhances the depth and richness of the light patterns, making the simulation more vibrant and visually appealing.
How It Works:

Choose Your Colors: Use the intuitive color picker to select your desired start and end colors for the gradient.
Apply to Patterns: The chosen gradient will be applied to all light patterns, whether you are using conic, radial, linear, or any of the additional modes like spiral or grid.
Dynamic Transition: As the lights dance, they will transition seamlessly through the colors in your gradient, creating a mesmerizing and continuous flow of hues.

### PR DESCRIPTION
**Pull request by sidharth2829**
Added a color gradient selector and appropriate form validation required
Screenshot 2024-05-31 at 6 47 16 PM
Screenshot 2024-05-31 at 7 20 37 PM
Screenshot 2024-05-31 at 7 21 52 PM

### CODE REVIEW

**Comment by sk66641** [comment]
@sidharth2829 
i actually misunderstood, i thought you would be adding a feature where users can select two or more colors based on which it will simulate the selected view (conic, linear or any) but it's ok 
Also there is an issue like when both the colors are same, it doesn't work even if i keep changing the number of colors.

**Comment by sidharth2829** [comment]
> @sidharth2829 i actually misunderstood, i thought you would be adding a feature where users can select two or more colors based on which it will simulate the selected view (conic, linear or any) but it's ok Also there is an issue like when both the colors are same, it doesn't work even if i keep changing the number of colors.

@sk66641, i will fix that issue and make sure if the user selects same color, then he/she gets an alert, and says he will see random colors if different colors are not selected.

And one more request, i just synced my fork and many changes have been made, so now i have to again analyse the whole code and make changes accordingly. So pls can you make sure that different issues doesn't conflict with each other.

**Comment by sidharth2829** [comment]
@sk66641 , i am creating a new pull request regarding the issue and merging the changes from main branch of my forked repository to your main branch, as my repo "my-branch" is giving too many conflicts when synced.

**Comment by sk66641** [comment]
@sidharth2829 
i have merged it #121

**Pull request closed without merging**
