### PR TITLE
Music added

### PR DESCRIPTION
**Pull request by arunimaChintu**
# Description
This adds music
Fixes:  #552 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### CODE REVIEW

**Comment by arunimaChintu** [comment]
@aditya-bhaumik Please merge this and please assign the levels and labels

**Review by aditya-bhaumik — APPROVED** [review]

**Comment by aditya-bhaumik** [comment]
@arunimaChintu please share a recording of what exactly this change does

i runned it in my local machine there is no change in the website

**Comment by arunimaChintu** [comment]
@aditya-bhaumik it adds music in it, the rest is same... I cant screen record with music in my system... but it works I have tested it...

**Comment by aditya-bhaumik** [comment]
@arunimaChintu isnt there already a feature for changing the background music i downloaded your code and tested it in my local machine 

Please provide a recording so that i can understand what new change is made

**Comment by aditya-bhaumik** [comment]
@sk66641 please review this pull request as i tested in local machine but cant find any change

**Comment by sk66641** [comment]
@arunimaChintu 
it seems you have simply added a music which autoplay on the loading of the page which is different from the issue #553

**Pull request closed without merging**
