### PR TITLE
Added scroll to top button with progress button

### PR DESCRIPTION
**Pull request by TheNikhilRaj**
**.. It's on all the pages**

# Description

Hey @sk66641 ,
I have noticed a small issue that I believe could enhance the user experience. Currently, there is no progress bar scroll to top button present on the website.

Fixes:  #350 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

Capture

@sk66641

### CODE REVIEW

**Comment by sk66641** [comment]
it can't be merged

**Comment by TheNikhilRaj** [comment]
> it can't be merged otherwise it'll remove all the changes made in previous prs

So what should i do @sk66641

**Comment by sk66641** [comment]
@TheNikhilRaj 
i understand it but how so many changes are coming. The changes should be only for adding progress in scroll to top button.

**Comment by sk66641** [comment]
@TheNikhilRaj 
i saw your forked repo and found that you have made another folder of Random Disco Light Simulator & that's creating this issue

**Pull request closed without merging**
