### PR TITLE
Added the logo

### LINKED ISSUE #20: Can add logo
Can add a customized logo in the navbar. Please assign it to me.

### PR DESCRIPTION
**Pull request by sweta-singh28**
Added a new logo on the top right corner closes #20.

### CODE REVIEW

**Comment by sk66641** [comment]
Hi! @sweta-singh28 you have sent a pull request without creating an issue and being assigned!

**Comment by sweta-singh28** [comment]
I was assigned this issue check issue no. 20.

**Comment by sk66641** [comment]
@sweta-singh28 that time you didn't mentioned the issue number! That's why i didn't get it!

**Comment by sweta-singh28** [comment]
Sir, now what to do? You have assigned the same task to issue number #49 which was created much later.

**Pull request merged**
