### PR TITLE
Fixed The Overlapping Chatbot and Scroll to Top Button

### LINKED ISSUE #492: BUG: Chatbot is overlapping the scroll to top button
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hey @sk66641 and @aditya-bhaumik 

On this website the chatbot is overlapping the scroll to top button

image

image

### Expected behavior

N/A

### Add ScreenShots

_No response_

### What browsers are you seeing the problem on?

_No response_

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by RadhikaMalpani1702**
# Description
Hey @sk66641 

- issue closes #492 

I have fixed the overlapping chatbot and scroll to top button

image

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings

### CODE REVIEW

**Comment by sk66641** [comment]
@RadhikaMalpani1702 
Now, it's overlapping with the sidebar
Screenshot from 2024-07-24 17-23-09

**Comment by RadhikaMalpani1702** [comment]
@sk66641 Then I will just remove the scroll to top button from the home page as it is not needed there? as the home page is short

**Comment by aditya-bhaumik** [comment]
@RadhikaMalpani1702 dont remove the scroll to top button instead put it above the chatbot in the main page

**Comment by sk66641** [comment]
> @RadhikaMalpani1702 dont remove the scroll to top button instead put it above the chatbot in the main page like in between the social icons and the chatbot

@RadhikaMalpani1702 yes it can be

**Comment by RadhikaMalpani1702** [comment]
@aditya-bhaumik and @sk66641 Okay i will do it

**Comment by RadhikaMalpani1702** [comment]
Hey @sk66641 and @aditya-bhaumik Made the changes

image

**Comment by aditya-bhaumik** [comment]
@RadhikaMalpani1702 there still many bugs like in small screen it is not visible and why is the back to top button is always visible but it should only be visible when the screen is scrolled down

@sk66641 can you please check this as i think this is introducting new bugs

**Comment by RadhikaMalpani1702** [comment]
@sk66641  @aditya-bhaumik If you can see the code changes what I have done then those are only CSS adjustments, the scroll to top button was like this already, please review the code changes
- I have only done CSS changes
- For small screens it is not visible because whoever made this button he did not add media properties 
- The button is always visible because its JavaScript code has that logic (I didn't even touched it) 
- lastly I raised the issue/bug for solving the overlapping of scroll to top button because of Chatbot 


I hope I was able to explain it to you! If you want it then I will fix it.

**Comment by aditya-bhaumik** [comment]
@RadhikaMalpani1702 yes for smaller screens you need to make css changes only check the website it is visible before you made the changes as for the other bug i checked it was already there so you dont need to fix that fix for the smaller screens as it was the css change which is caused it to disappear from the smaller screens

**Comment by RadhikaMalpani1702** [comment]
@aditya-bhaumik Sure, I will make the changes!

**Comment by aditya-bhaumik** [comment]
@RadhikaMalpani1702 okay you can try making changes to the javascript logic so that the button is visible only when we sroll down and when we press on it it should go back up and also the smaller screen fix 

I will update the issue level to 3 after these changes

**Comment by RadhikaMalpani1702** [comment]
@aditya-bhaumik Done the changes the scroll to top button is now appears only when scroll down a bit (Except home page as before) and on click it smoothly scrolls up to the page

**Comment by aditya-bhaumik** [comment]
can you send a recording showing it please

**Review by aditya-bhaumik — APPROVED** [review]

**Pull request merged**
