### PR TITLE
changed ui of form on main page #236

### PR DESCRIPTION
**Pull request by kritzxd8**
hello @sk66641  I have worked on #236 .
this is how it looks :   
Screenshot 2024-06-14 005529

i have kept the changing heading as it is 
so kindly let me know if u want some changes in this.
thank you.

### CODE REVIEW

**Comment by sk66641** [comment]
@kritzxd8 
The changes you have made are really nice but it's not responsive. I have attached an image for the reference.
test

**Comment by kritzxd8** [comment]
@sk66641 yea sure i'll make those changes

**Comment by kritzxd8** [comment]
hello @sk66641  i have successfully made the changes u pointed out .

Screenshot 2024-06-15 223137

Kindly check !!

**Comment by sk66641** [comment]
@kritzxd8 
Nice work!

**Pull request merged**
