### PR TITLE
Issue #510

### PR DESCRIPTION
**Pull request by Jasleen1210**
# Description

Used session storage to enable the loader only once per session, i.e. avoid loader when the user navigates to the home page from other side pages 

Accordingly adjusted the display of back to top button, nav menu and the warning modal ensuring that the set time out function on these elements is not executed on instances other than initial load

Fixes:  #510 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### CODE REVIEW

**Comment by sk66641** [comment]
@Jasleen1210 
sometimes simulation doesn't work after successful submission

https://github.com/user-attachments/assets/90cb43b9-acb9-42f5-b6f2-69868edb7781

**Comment by Jasleen1210** [comment]
@sk66641 Ive tried re-running on multiple browsers but im not facing the same issue, can you tell me more about when did you encounter it and what was the error in the console at that time?

**Comment by aditya-bhaumik** [comment]
@Jasleen1210 i think it is not running after we first use the simulation then go back to the main screen then again try to run the simulation

**Comment by Jasleen1210** [comment]
@aditya-bhaumik could you tell me what you see in the console at the time? and confirm the browser you use? i still havent encountered the issue and i can't find any logic issue in the code that could be causing the same either

**Comment by sk66641** [comment]
@Jasleen1210 

https://github.com/user-attachments/assets/04750de2-40dc-445c-b24f-f67d2d8bc194

**Comment by aditya-bhaumik** [comment]
@Jasleen1210 have fixed the problem ?? also there conflicts in the pr now fix that also

**Comment by Jasleen1210** [comment]
@aditya-bhaumik resolved the conflicts but i haven't been able to get rid of the issue, the code stops at the line where chatbot display is hidden and if i change the positioning of that line more issues are created

**Comment by aditya-bhaumik** [comment]
@Jasleen1210 i am closing this pull request as for the moment you can work on your other issues when you solve this problem you can raise another pull request

**Pull request closed without merging**
